class WordList:
    wordlist = ["godly","complain","barbarous","lewd","railway",
"beginner","hat","aback","secret","sea","fat","loss","test","box","meat","yummy","cows","spurious","poke","unnatural","bawdy","mushy",
"flavor","pickle","imminent","curious","wealthy","alleged","enthusiastic","drab","glue","squalid","erratic","sip","protest","collect",
"polite""rest","share","chilly","left","vest","vacuous","crayon","frog","admire","aquatic","green","circle","cowardly","manage","resolute",
"taboo","pricey","form","tooth","idiotic","risk","colorful","puffy","ossified","glass","grateful","annoy","tax","maddening","stream","exercise","minute","melt","plantation","hair","tiger","stuff",
"silent","befitting","substance","hurry","size","slope","scold","maniacal","frantic","carve","ragged","treatment",
"orange","harsh","slip","ring","safe","wet","wobble","show","boat","calculator","zephyr","industrious","respect","light",
"bloody","join","lake","tiny","false","awake","mute","upset","lip","spring","iron","rural","reflect","blush","dime","fretful","regular","square","ink","homeless",
"psychotic","victorious","gleaming","fortunate","voice","hour","voiceless","blink","tranquil","bubble","vague","obnoxious","friends","important","rabbit","stingy","rail","robin",
"egg","squealing","tested","deserted","daily","moldy","bead","shame","treat","typical","delicious","cooperative",
"look","didactic","greet","shelf","elite","thing","lick","meaty","believe","coil","permit","reward","transport","meeting","steam","able","past","bump","labored",
"play","three","majestic","ban","momentous","food","diligent","useful","overconfident","loaf","aftermath","view",
"skillful","flimsy","mind","spotty","purpose","nose","agree","supply","shut","harm","practice","notebook","smiling",
"waiting","history","faithful","wing","determined","thoughtful","division","explode","tasteless",
"wrist","chief","silk","adhesive","uppity","scared","correct","chase","learned","deceive","substantial","money","lamentable","jail","charming","spare","bruise",
"tasteful","press","provide","empty","condemned","terrify","muscle","extend","dry","geese","suggestion","volleyball","polish",
"wax","skirt","fragile","various","damage","post","tempt","futuristic","snatch","yielding",
"eight","sound","splendid","shivering","sleep","possessive","gratis","proud","chop","abiding","bouncy",
"familiar","null","lazy","symptomatic","pump","fade","ignorant","sweet","filthy","abrupt","governor","understood",
"well-made","youthful","please","faded","enjoy","blue","veil","hard","leg","club","border","wonder",
"rude","massive","screw","tick","mouth","debonair","authority","dare","romantic","unusual","unsuitable",
"activity","puzzling","talented","selfish","crook","ordinary","writer","injure","ashamed","melodic","behavior"]